---

kind: pipeline
type: docker
name: Network-Multitool-alpine-extra

platform:
  os: linux
  arch: amd64

steps:
- name: Trigger
  image: plugins/git
  commands:
    - test $DRONE_BUILD_EVENT = pull_request
      && DIFF_STRING=origin/${DRONE_COMMIT_BRANCH:-alpine-extra}
      || DIFF_STRING=${DRONE_COMMIT_SHA}~
    - git --no-pager diff --name-only $DIFF_STRING
      | grep -q -e ^Dockerfile
      || exit 78

- name: Build
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    repo: modem7/network-multitool
    purge: true
    compress: true
    use_cache: true
    build_args: BUILDKIT_INLINE_CACHE=1
    cache_from: 
      - modem7/network-multitool:alpine-extra
    platforms: # if it doesn't work run docker run --privileged --rm tonistiigi/binfmt --install all
      - linux/amd64
      - linux/arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - alpine-extra

- name: slack
  image: themaz/drone-slack
  settings:
    webhook:
      from_secret: slack_hook
  when:
    status: [ success, failure ]

trigger:
  branch:
    - alpine-extra
  event:
    include:
    - push
    - custom